language: csharp
solution: OmegaSplicer.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore OmegaSplicer.sln
after_script:
  - nunit-console Tests/bin/Release/Tests.dll
