# Travis-CI Build for OmegaSlicer
# see travis-ci.org for details 

language: c 

install:
 - sudo apt-get update -qq
 - sudo apt-get install -y mono-devel mono-gmcs nunit-console libfbembed2.5

script: 
 - xbuild CI.proj 
